spring.application.name=store
# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/store?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=mondongo
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
# Cargar schema.sql y data.sql al iniciar
spring.sql.init.mode=never
spring.sql.init.data-locations=classpath:data.sql